spring.application.name=gerenciador-eventos

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}
# driver
spring.datasource.driver-class-name=org.postgresql.Driver

#token jwt
jwt.secret=${JWT_SECRET}